version = 1

[[annotations]]
path = [
  ".gas-snapshot",
  ".github/workflows/**/",
  ".gitignore",
  ".gitmodules",
  "CLAUDE.md",
  "README.md",
  "audit/**/",
  "flake.lock",
  "flake.nix",
  "foundry.toml",
  "slither.config.json",
  "REUSE.toml",
  "foundry.lock",
  "remappings.txt",
  "soldeer.lock",
  ".soldeerignore",
]
SPDX-FileCopyrightText = "Copyright (c) 2020 thedavidmeister"
SPDX-License-Identifier = "LicenseRef-DCL-1.0"
